# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerStudent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='studentdetailsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
