# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import registerStudent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registerStudent', '0002_auto_20171121_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailsmodel',
            name='registrationNumber',
            field=models.IntegerField(default=1, unique=True, validators=[registerStudent.validators.validate_registration]),
        ),
        migrations.AlterField(
            model_name='studentdetailsmodel',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
