# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import registerStudent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registerStudent', '0003_auto_20171228_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailsmodel',
            name='registrationNumber',
            field=models.IntegerField(unique=True, validators=[registerStudent.validators.validate_registration]),
        ),
    ]
