# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import registerStudent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('registerStudent', '0004_auto_20171228_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailsmodel',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='Valid email please!'),
        ),
        migrations.AlterField(
            model_name='studentdetailsmodel',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Your name according to ID'),
        ),
        migrations.AlterField(
            model_name='studentdetailsmodel',
            name='registrationNumber',
            field=models.IntegerField(default=9207425, unique=True, validators=[registerStudent.validators.validate_registration]),
        ),
    ]
